name: PHPStan

on:
  push:
    branches: [ wiki ]
  pull_request:
    branches: [ wiki ]

jobs:
  phpstan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: PHPStan
        uses: chindit/actions-phpstan@master
